$gregIsms = New-Object System.Collections.ArrayList
$gregIsms.add("COME ON PHOTOSHOP")
$gregIsms.add("Ya buzzards")
$gregIsms.add("Awww SNOOPS")
$gregIsms.add("Hes a nice cat")
$gregIsms.add("Smells in here")
$gregIsms.add("Your getting sorted")
$gregIsms.add("SHUT UP")
$gregIsms.add("YOU SHUT UP")
$gregIsms.add("This chat room died on its arse")
$gregIsms.add("Oh man the bathroom")
$gregIsms.add("My stomach hurts")
$gregIsms.add("My head hurts")
$gregIsms.add("My back hurts")
$gregIsms.add("Im going to CitiMD")
$gregIsms.add("CRUUUUUUUUUUUUUUUZ")
$gregIsms.add("gross")
$gregIsms.add("there was a homeless man at wholefoods touching the salad")
$gregIsms.add("that darn (pness2)")
$gregIsms.add("anyone want a cold one")
$gregIsms.add("wheres skeete?")
$gregIsms.add("someone was blowing their colon in the bathroom")
$gregIsms.add("that girl")
$gregIsms.add("get back to work")
$gregIsms.add("fukin (pness2)")
$gregIsms.add("ethnics")
$gregIsms.add("whens payday")
$gregIsms.add("are you getting a cold one after work?")
$gregIsms.add("get in there my son")
$gregIsms.add("skeets")
$gregIsms.add("anyone wanna go for a cold one")
$gregIsms.add("cold ones????")
$gregIsms.add("(pbr)")
$gregIsms.add("damn")
$gregIsms.add("when do we get paid")
$gregIsms.add("wasky")
$gregIsms.add("wasky has asked you to clean out your crap food!!!")
$gregIsms.add("fuckin NESS")
$gregIsms.add("windell is going to the glory hole")
$gregIsms.add("you funky prawns")
$gregIsms.add("anybody wanna go to tracks bar??")
$gregIsms.add("smash that updoot")
$gregIsms.add("should ness make yummi pay rent now that they are married?")
$gregIsms.add("sick + scrum")
$gregIsms.add("CRUZZZZ + scrum")
$gregIsms.add("that girl is coming over later")
$gregIsms.add("Massive delays on 1 2 3 trains I need to grab the A")
$gregIsms.add("BIG DOM")
$gregIsms.add("We cant fight amongst ourselves")
$gregIsms.add("I may have a stomachache")
$gregIsms.add("whats the bottom shelf beer? whats the top shelf beer? and are the small bites split into two levels?")
$gregIsms.add("Running a bit late this am")
$gregIsms.add("I slept through my alarm and I feel like crud. I'm gonna stay home today")
$gregIsms.add("I have the chills sweating fever body aches sore throat symptoms if I don't feel better in a few hours I'm staying home.")
$gregIsms.add("Whatcha getting... BUUUURRRGAAAAAAAAAAAAAAR?")
$gregIsms.add("I have a terrible headache I'm staying home. If anything urgent comes up txt me I prolly won't look at email today")
$gregIsms.add("mike strong was lettin LOOSE")
$gregIsms.add("NOOCH")
$gregIsms.add("Im gonna kick you in the nooch")
$gregIsms.add("you buttholes")
$gregIsms.add("someone blotted their ass on this napkin")
$gregIsms.add("I need a taste")
$gregIsms.add("what are you bozos doin")
$gregIsms.add("it smelled like friggin boiled ham in the bathroom")
$gregIsms.add("My stomach is whacked this am. Im going to wait it out and come in around 10.30-11am")
$gregIsms.add("you pickle sniffers")
$gregIsms.add("Signal problem I have to get a taxi in")
$gregIsms.add("im goin to hr for that comment")
$gregIsms.add("I'm feeling junky and will work from my bed. I'll be online in 10-15 mins.")

function SendGreg ($gregIsm) {
	$body = '{"color":"green","message": "' + $gregIsm + '","notify":false,"message_format":"text"}'
	curl -Body $body   -Method POST `
	-ContentType application/json `
	-URI https://yourhipchatroom
}
SendGreg $gregIsms[(Get-Random -minimum 0 -maximum 90)]